const cars = [
    {
        _id: '1',
        model: 'Creta',
        brand: 'Hyundai',
        image: '/images/car.jpg',
        type: 'suv',
        isUsed: false,
        kmsDriven: null,
        age: null,
        city: null,
        isAvailable: null,
        priceRange: [
            { variant: 'ex', price: 1100000 },
            { variant: 's', price: 1400000 },
            { variant: 'sx', price: 1700000 },
            { variant: 'sx(o)', price: 2100000 },
          ],
    },
    {
        _id: '2',
        model: 'i20',
        brand: 'Hyundai',
        image: '/images/car.jpg',
        type: 'hatchback',
        isUsed: false,
        kmsDriven: null,
        age: null,
        city: null,
        isAvailable: null,
        priceRange: [
            { variant: 'era', price: 850000 },
            { variant: 'asta', price: 1000000 },
            { variant: 'sportz', price: 1300000 },
          ],
    },
    {
        _id: '3',
        model: 'City',
        brand: 'Honda',
        image: '/images/car.jpg',
        type: 'sedan',
        isUsed: true,
        kmsDriven: 47000,
        age: 4,
        city: 'Pune',
        isAvailable: true,
        priceRange: [
            { variant: 'zx', price: 1300000 },
          ],
    },
    {
        _id: '4',
        model: 'Innova Crysta',
        brand: 'Toyota',
        image: '/images/car.jpg',
        type: 'muv',
        isUsed: true,
        kmsDriven: 69000,
        age: 3,
        city: 'Mumbai',
        isAvailable: true,
        priceRange: [
            { variant: 'gx', price: 1900000 },
          ],
    },
    {
        _id: '5',
        model: 'Seltos',
        brand: 'Kia',
        image: '/images/car.jpg',
        type: 'suv',
        isUsed: false,
        kmsDriven: null,
        age: null,
        city: null,
        isAvailable: null,
        priceRange: [
            { variant: 'htk', price: 1150000 },
            { variant: 'htx', price: 1700000 },
            { variant: 'gtx', price: 2120000 },
          ],
    },
    {
        _id: '6',
        model: 'Ertiga',
        brand: 'Maruti Suzuki',
        image: '/images/car.jpg',
        type: 'muv',
        isUsed: false,
        kmsDriven: null,
        age: null,
        city: null,
        isAvailable: null,
        priceRange: [
            { variant: 'lx', price: 1050000 },
            { variant: 'vx', price: 1192000 },
            { variant: 'zx', price: 1367000 },
          ],
    },
  ]
  
  export default cars